apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-glhweb-com
  labels:
    app: home-glhweb-com
spec:
  replicas: 3 # Number of instances
  selector:
    matchLabels:
      app: home-glhweb-com
  template:
    metadata:
      labels:
        app: home-glhweb-com
    spec:
      containers:
        - name: home-glhweb-com
          # This is where the magic happens! The image tag will be updated by your CD pipeline.
          image: ghcr.io/gabriel-lau/home.glhweb.com:main
          ports:
            - containerPort: 3000 # Must match EXPOSE in Dockerfile
          resources: # Request and limit resources
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
