# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build
    #   - run: npm test

    # WHEN TESTS PASS THE PROJECT WILL BE BUILT IN DOCKER

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    #   - name: Set up Docker Buildx
    #     id: buildx
    #     uses: docker/setup-buildx-action@v2

    #   - name: Build and push
    #     id: docker_build
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       file: Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/home.glhweb.com

    #   - name: Image digest
    #     run: echo ${{ steps.docker_build.outputs.digest }}
